[package]
name = "rogue-rs"
version = "0.1.0"
authors = ["MindM <maindi66@gmail.com>"]

[dependencies]
tcod = "0.12"
rand = "0.4"
pathfinding = "0.6"
recs = "2.0.1"
#time = "*"
serde = "1.0.27"
serde_json = "1.0"
serde_derive = "1.0.27"
derive-new = "0.5"